### PR TITLE
Set PlaceHolder when get Firebase EmailAddress

### PR DESCRIPTION
**Pull request by Hiroki0613**
When logging in to google, add an email address from the beginning on the opening application screen.
https://youtu.be/tam4sved2tk

### CODE REVIEW

**Comment by Hiroki0613** [comment]
Issue
https://github.com/KingdomSeekersJP/salon_app/issues/8

**Comment by dragonfly91** [comment]
Maybe think about making the email address Text widget to look a bit more read-only and suggest to the user that it is clearly a non-editable field?
Screen Shot 2021-10-31 at 16 25 39

**Review by dragonfly91 — APPROVED** [review]
left one comment please check

**Review by dragonfly91 — APPROVED** [review]
LGTM

**Pull request merged**
